pageObjectHW
Yanina666/AQA pull request #4
Opened 2023-07-23 10:27 UTC by Yanina666

2023-07-23 12:23 UTC, wildpioneer requested changes

2023-07-23 12:23 UTC, wildpioneer commented on src/test/resources/config.properties
> +timeout=15
Отсутствует файл ReadMe.md с описанием теста

2023-07-23 12:23 UTC, wildpioneer commented on src/test/java/tests/E2ETest.java
> +
Тест явно не закончен

2023-07-23 12:23 UTC, wildpioneer commented on src/test/java/pages/LoginPageHW.java
> +public class LoginPageHW extends BasePage {
Зачем постфикс HW в названии этого класса?

2023-07-23 12:23 UTC, wildpioneer commented on src/test/java/steps/E2ESteps.java
> +//    public ComplitePage finishingTheShopping(){
???

2023-07-23 12:23 UTC, wildpioneer commented on src/test/java/steps/E2ESteps.java
> +public class E2ESteps extends BaseStep {
А если это будут шаги для других тестов - не для e2e, то как будет называться класс?

2023-07-23 12:23 UTC, wildpioneer commented on src/test/java/steps/E2ESteps.java
> +    public SwagLabsPage successLogin(String username, String psw){
У тебя же есть LoginSteps класс - следовательно этот шаг должен быть там.

2023-07-23 12:35 UTC, Yanina666 commented on src/test/resources/config.properties
> +timeout=15
я сделала через пару минут после коммита и заново пушанула, просто не думала, что вы сразу проверять будете, посмотрите еще раз, пожалуйста

2023-07-23 13:06 UTC, Yanina666 commented on src/test/java/tests/E2ETest.java
> +
добавила проверку на страницу с завершением заказа

2023-07-23 13:07 UTC, Yanina666 commented on src/test/java/pages/LoginPageHW.java
> +public class LoginPageHW extends BasePage {
а черт его знает

2023-07-23 13:08 UTC, Yanina666 commented on src/test/java/steps/E2ESteps.java
> +//    public ComplitePage finishingTheShopping(){
здесь на что вопросы? на какую строчку?

2023-07-23 13:09 UTC, Yanina666 commented on src/test/java/steps/E2ESteps.java
> +public class E2ESteps extends BaseStep {
там и буду думать, пока задание было таким - e2e

2023-07-23 15:10 UTC, wildpioneer commented on src/test/java/steps/E2ESteps.java
> +//    public ComplitePage finishingTheShopping(){
Именно на ту - на которую добавлен коммент - 32

Вопрос в том - что это за закоментированный код?? Что он тут делает?

2023-07-23 15:16 UTC, wildpioneer requested changes

2023-07-23 15:16 UTC, wildpioneer commented on src/test/java/tests/E2ETest.java
> +        Assert.assertTrue(e2eSteps.finishThePurchase().isPageOpened());
В тесте не надо каждый шаг добавлять в assert  - только в конце теста ты проверяешь важное условие. В данном случае - проверка появления ComplitePage можно (но с нятяжкой) считать финальной проверкой

2023-07-23 15:16 UTC, wildpioneer commented on README.md
> +1.������� �� ������ https://www.saucedemo.com
С кодировкой надо что-то сделать.
https://www.jetbrains.com/help/idea/encoding.html

2023-08-07 15:39 UTC, wildpioneer commented
Проверено

2023-08-07 15:39 UTC, closed without merging